In [4]:
%matplotlib inline
import numpy as np
import pandas as pd


In [5]:
# How likely is it that you roll doubles when rolling two dice?

In [15]:
n_trials = nrows = 10_000
n_dice = ncols = 1

In [19]:
die1 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
die2 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
die1, die2

(array([[1],
        [4],
        [4],
        ...,
        [3],
        [1],
        [4]]),
 array([[2],
        [3],
        [1],
        ...,
        [6],
        [6],
        [1]]))

In [20]:
sum_double = die1 == die2
sum_double.sum()

In [25]:
probability = sum_double.mean()
probability

0.1618

In [ ]:
# If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [55]:
n_trials = nrows = 8
n_coin = ncols = 1

In [56]:
flips = np.random.choice([1, 0], n_trials * n_coin).reshape(nrows, ncols)
# 0 is equal to heads and 1 is equal to tails

In [57]:
flips

array([[0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1]])

In [58]:
head3 = flips == 0
head3.sum()

5

In [59]:
head3.mean()

0.625

In [ ]:
# There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [79]:
data_cohort = 1
bill_board = ncol = 2
n_trials = nrow = 10_000

In [80]:
data = np.random.choice(4, nrow * ncol).reshape(nrow, ncol)
data

array([[2, 3],
       [1, 3],
       [2, 2],
       ...,
       [1, 3],
       [3, 2],
       [3, 3]])

In [81]:
(pd.DataFrame(data)
 .apply(lambda row: row[0] == row[1] == 1, axis=1).mean())

0.0655